server:
  port: 8080
#  servlet:
#    session:
#      cookie:
#        domain: localhost
spring:
  application:
    name: portal
  data: 
    redis:
      host: localhost
      port: 6379
      database: 0
  security:
    oauth2:
      client:
        registration:
          my-client:
            client-id: my-client
            client-secret: my-secret
            scope: openid,read
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8080/login/oauth2/code/my-client"
            client-authentication-method: client_secret_basic
            provider: my-provider
        provider:
          my-provider:
#            authorization-uri: http://localhost:8081/oauth2/authorize
#            token-uri: http://localhost:8081/oauth2/token
#            user-info-uri: http://localhost:8081/userinfo
#            jwk-set-uri: http://localhost:8081/oauth2/jwks
            issuer-uri: http://localhost:8081
logging:
  level:
    "[org.springframework.security]": DEBUG
    "[org.springframework.web]": DEBUG
